#!/bin/bash
iser=$(cat /root/.isp)
if [[ $iser -gt 0 ]]; then
curl "ipinfo.io/org?token=8704ac9cf99c0a" > /root/.isp
else
echo ""
fi

iser1=$(cat /root/.city)
if [[ $iser -gt 0 ]]; then
curl "ipinfo.io/city?token=8704ac9cf99c0a" > /root/.city
else
echo ""
fi
